// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.API.Persistence.Contexts;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200307222500_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DispenserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Login = "Andrzej",
                            Password = "Tak1223"
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 100,
                            Login = "Moze",
                            Password = "Byc"
                        },
                        new
                        {
                            Id = 3,
                            DispenserId = 100,
                            Login = "Ten",
                            Password = "Trzeci"
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 101,
                            Login = "Oraz",
                            Password = "Czw"
                        },
                        new
                        {
                            Id = 5,
                            DispenserId = 102,
                            Login = "Koko",
                            Password = "Ro"
                        },
                        new
                        {
                            Id = 6,
                            DispenserId = 1002,
                            Login = "Zepsute",
                            Password = "Konto"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Dispenser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("TurnDiode")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Dispensers");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Cos",
                            TurnDiode = false
                        },
                        new
                        {
                            Id = 101,
                            Name = "Tam",
                            TurnDiode = true
                        },
                        new
                        {
                            Id = 102,
                            Name = "Yayy",
                            TurnDiode = false
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.HasOne("WebApplication1.API.Domain.Models.Dispenser", "Dispensers")
                        .WithMany()
                        .HasForeignKey("DispenserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
