// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.API.Persistence.Contexts;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200316143143_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Login = "Andrzej",
                            Password = "Tak1223"
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 100,
                            Login = "Moze",
                            Password = "Byc"
                        },
                        new
                        {
                            Id = 3,
                            DispenserId = 100,
                            Login = "Ten",
                            Password = "Trzeci"
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 101,
                            Login = "Oraz",
                            Password = "Czw"
                        },
                        new
                        {
                            Id = 5,
                            DispenserId = 102,
                            Login = "Koko",
                            Password = "Ro"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Dispenser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<string>("Nr_Okienka")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dispensers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Nr_Okienka = "1010011"
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 102,
                            Nr_Okienka = "1001001"
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 103,
                            Nr_Okienka = "1011101"
                        },
                        new
                        {
                            Id = 5,
                            DispenserId = 104,
                            Nr_Okienka = "1001001"
                        },
                        new
                        {
                            Id = 6,
                            DispenserId = 105,
                            Nr_Okienka = "0001000"
                        },
                        new
                        {
                            Id = 7,
                            DispenserId = 106,
                            Nr_Okienka = "0001001"
                        },
                        new
                        {
                            Id = 8,
                            DispenserId = 107,
                            Nr_Okienka = "0001100"
                        },
                        new
                        {
                            Id = 9,
                            DispenserId = 108,
                            Nr_Okienka = "0101010"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<int>("Flaga")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Okienka")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Flaga = 0,
                            Nr_Okienka = 1,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 3, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Flaga = 1,
                            Nr_Okienka = 2,
                            Opis = "Iladian"
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 8, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Flaga = 0,
                            Nr_Okienka = 3,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2020, 3, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 103,
                            Flaga = 1,
                            Nr_Okienka = 4,
                            Opis = "Limetic"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Okienka")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 3, 9, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 1,
                            Opis = "Apap"
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 3, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 2,
                            Opis = "Apap"
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 11, 3, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 3,
                            Opis = "Apap"
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2020, 3, 9, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 4,
                            Opis = "IBUM"
                        },
                        new
                        {
                            Id = 5,
                            DateAndTime = new DateTime(2020, 3, 10, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 5,
                            Opis = "IBUM"
                        },
                        new
                        {
                            Id = 6,
                            DateAndTime = new DateTime(2020, 3, 11, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 6,
                            Opis = "IBUM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
