// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.API.Persistence.Contexts;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200318155929_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Login = "AndrzejKrawczyk",
                            Password = "Tak123"
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 102,
                            Login = "MateuszWałek",
                            Password = "Nie321"
                        },
                        new
                        {
                            Id = 3,
                            DispenserId = 103,
                            Login = "TomekKowalski",
                            Password = "Haslo"
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 104,
                            Login = "PawełNowak",
                            Password = "Test"
                        },
                        new
                        {
                            Id = 5,
                            DispenserId = 105,
                            Login = "JakubLewandowski",
                            Password = "Somsiad"
                        },
                        new
                        {
                            Id = 6,
                            DispenserId = 106,
                            Login = "MarekPracowity",
                            Password = "Viagra"
                        },
                        new
                        {
                            Id = 7,
                            DispenserId = 107,
                            Login = "FranekGolas",
                            Password = "Wojna"
                        },
                        new
                        {
                            Id = 8,
                            DispenserId = 108,
                            Login = "AdamMickiewicz",
                            Password = "Pisarz"
                        },
                        new
                        {
                            Id = 9,
                            DispenserId = 109,
                            Login = "JanKazimierzKretacz",
                            Password = "Test109"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Dispenser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<string>("Nr_Okienka")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dispensers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Nr_Okienka = "1110000"
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 102,
                            Nr_Okienka = "1010100"
                        },
                        new
                        {
                            Id = 3,
                            DispenserId = 103,
                            Nr_Okienka = "0100010"
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 104,
                            Nr_Okienka = "1000000"
                        },
                        new
                        {
                            Id = 5,
                            DispenserId = 105,
                            Nr_Okienka = "0000001"
                        },
                        new
                        {
                            Id = 6,
                            DispenserId = 106,
                            Nr_Okienka = "0001000"
                        },
                        new
                        {
                            Id = 7,
                            DispenserId = 107,
                            Nr_Okienka = "1000001"
                        },
                        new
                        {
                            Id = 8,
                            DispenserId = 108,
                            Nr_Okienka = "0001001"
                        },
                        new
                        {
                            Id = 9,
                            DispenserId = 109,
                            Nr_Okienka = "1000010"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<int>("Flaga")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Okienka")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 109,
                            Flaga = 0,
                            Nr_Okienka = 1,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 3, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 108,
                            Flaga = 1,
                            Nr_Okienka = 2,
                            Opis = "Iladian"
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 107,
                            Flaga = 0,
                            Nr_Okienka = 3,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2020, 3, 2, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 106,
                            Flaga = 1,
                            Nr_Okienka = 4,
                            Opis = "Limetic"
                        },
                        new
                        {
                            Id = 5,
                            DateAndTime = new DateTime(2020, 3, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 105,
                            Flaga = 1,
                            Nr_Okienka = 5,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 6,
                            DateAndTime = new DateTime(2020, 3, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 104,
                            Flaga = -1,
                            Nr_Okienka = 6,
                            Opis = "Iladian"
                        },
                        new
                        {
                            Id = 7,
                            DateAndTime = new DateTime(2020, 3, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 103,
                            Flaga = 1,
                            Nr_Okienka = 7,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 8,
                            DateAndTime = new DateTime(2020, 3, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Flaga = 1,
                            Nr_Okienka = 1,
                            Opis = "Limetic"
                        },
                        new
                        {
                            Id = 9,
                            DateAndTime = new DateTime(2020, 3, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Flaga = 1,
                            Nr_Okienka = 1,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 10,
                            DateAndTime = new DateTime(2020, 3, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Flaga = -1,
                            Nr_Okienka = 2,
                            Opis = "Iladian"
                        },
                        new
                        {
                            Id = 11,
                            DateAndTime = new DateTime(2020, 3, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 103,
                            Flaga = 1,
                            Nr_Okienka = 2,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 12,
                            DateAndTime = new DateTime(2020, 3, 4, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 104,
                            Flaga = 0,
                            Nr_Okienka = 3,
                            Opis = "Limetic"
                        },
                        new
                        {
                            Id = 13,
                            DateAndTime = new DateTime(2020, 3, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 105,
                            Flaga = 1,
                            Nr_Okienka = 3,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 14,
                            DateAndTime = new DateTime(2020, 3, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 106,
                            Flaga = -1,
                            Nr_Okienka = 4,
                            Opis = "Iladian"
                        },
                        new
                        {
                            Id = 15,
                            DateAndTime = new DateTime(2020, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 107,
                            Flaga = 1,
                            Nr_Okienka = 5,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 16,
                            DateAndTime = new DateTime(2020, 3, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 108,
                            Flaga = 1,
                            Nr_Okienka = 6,
                            Opis = "Limetic"
                        },
                        new
                        {
                            Id = 17,
                            DateAndTime = new DateTime(2020, 3, 6, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 109,
                            Flaga = 1,
                            Nr_Okienka = 7,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 18,
                            DateAndTime = new DateTime(2020, 3, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 109,
                            Flaga = -1,
                            Nr_Okienka = 1,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 19,
                            DateAndTime = new DateTime(2020, 3, 7, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 109,
                            Flaga = 1,
                            Nr_Okienka = 2,
                            Opis = "Iladian"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Okienka")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 3, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Nr_Okienka = 1,
                            Opis = "Apap"
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 3, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Nr_Okienka = 2,
                            Opis = "Apap"
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Nr_Okienka = 3,
                            Opis = "Apap"
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2020, 3, 20, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 1,
                            Opis = "IBUM"
                        },
                        new
                        {
                            Id = 5,
                            DateAndTime = new DateTime(2020, 3, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 3,
                            Opis = "IBUM"
                        },
                        new
                        {
                            Id = 6,
                            DateAndTime = new DateTime(2020, 3, 21, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Nr_Okienka = 5,
                            Opis = "IBUM"
                        },
                        new
                        {
                            Id = 7,
                            DateAndTime = new DateTime(2020, 3, 20, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 103,
                            Nr_Okienka = 2,
                            Opis = "aaa"
                        },
                        new
                        {
                            Id = 8,
                            DateAndTime = new DateTime(2020, 3, 20, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 103,
                            Nr_Okienka = 6,
                            Opis = "aaa"
                        },
                        new
                        {
                            Id = 9,
                            DateAndTime = new DateTime(2020, 3, 20, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 104,
                            Nr_Okienka = 1,
                            Opis = "bbb"
                        },
                        new
                        {
                            Id = 10,
                            DateAndTime = new DateTime(2020, 3, 20, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 105,
                            Nr_Okienka = 7,
                            Opis = "ccc"
                        },
                        new
                        {
                            Id = 11,
                            DateAndTime = new DateTime(2020, 3, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 106,
                            Nr_Okienka = 4,
                            Opis = "ddd"
                        },
                        new
                        {
                            Id = 12,
                            DateAndTime = new DateTime(2020, 3, 20, 1, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 107,
                            Nr_Okienka = 1,
                            Opis = "brain"
                        },
                        new
                        {
                            Id = 13,
                            DateAndTime = new DateTime(2020, 3, 20, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 107,
                            Nr_Okienka = 7,
                            Opis = "brain"
                        },
                        new
                        {
                            Id = 14,
                            DateAndTime = new DateTime(2020, 3, 20, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 108,
                            Nr_Okienka = 4,
                            Opis = "lol"
                        },
                        new
                        {
                            Id = 15,
                            DateAndTime = new DateTime(2020, 3, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 108,
                            Nr_Okienka = 7,
                            Opis = "lol"
                        },
                        new
                        {
                            Id = 16,
                            DateAndTime = new DateTime(2020, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 109,
                            Nr_Okienka = 1,
                            Opis = "Eutanazol"
                        },
                        new
                        {
                            Id = 17,
                            DateAndTime = new DateTime(2020, 3, 20, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 109,
                            Nr_Okienka = 6,
                            Opis = "Eutanazol"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
