// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.API.Persistence.Contexts;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200322144059_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeAccount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "TestGuy123",
                            Name = "Andrzej Krawczyk",
                            Password = "Tak123",
                            TypeAccount = 1
                        },
                        new
                        {
                            Id = 2,
                            Login = "TG123456",
                            Name = "Mateusz Wałek",
                            Password = "Nie321",
                            TypeAccount = 1
                        },
                        new
                        {
                            Id = 3,
                            Login = "TTeesstt",
                            Name = "Tomek Kowalski",
                            Password = "Haslo",
                            TypeAccount = 1
                        },
                        new
                        {
                            Id = 4,
                            Login = "Tetestst",
                            Name = "Paweł Nowak",
                            Password = "Test",
                            TypeAccount = 1
                        },
                        new
                        {
                            Id = 5,
                            Login = "GuyGuyGuy",
                            Name = "Jakub Lewandowski",
                            Password = "Somsiad",
                            TypeAccount = 1
                        },
                        new
                        {
                            Id = 6,
                            Login = "TempTemp",
                            Name = "Marek Pracowity",
                            Password = "Viagra",
                            TypeAccount = 3
                        },
                        new
                        {
                            Id = 7,
                            Login = "TestAccount",
                            Name = "Franek Golas",
                            Password = "Wojna",
                            TypeAccount = 2
                        },
                        new
                        {
                            Id = 8,
                            Login = "qwerty",
                            Name = "Adam Mickiewicz",
                            Password = "Pisarz",
                            TypeAccount = 2
                        },
                        new
                        {
                            Id = 9,
                            Login = "qwerty123",
                            Name = "Jan Kazimierz Kretacz",
                            Password = "Test109",
                            TypeAccount = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Dispenser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDispenser")
                        .HasColumnType("int");

                    b.Property<string>("NoWindow")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dispensers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdDispenser = 101,
                            NoWindow = "1110000"
                        },
                        new
                        {
                            Id = 2,
                            IdDispenser = 102,
                            NoWindow = "1010100"
                        },
                        new
                        {
                            Id = 3,
                            IdDispenser = 103,
                            NoWindow = "0100010"
                        },
                        new
                        {
                            Id = 4,
                            IdDispenser = 104,
                            NoWindow = "1000000"
                        },
                        new
                        {
                            Id = 5,
                            IdDispenser = 105,
                            NoWindow = "0000001"
                        },
                        new
                        {
                            Id = 6,
                            IdDispenser = 106,
                            NoWindow = "0001000"
                        },
                        new
                        {
                            Id = 7,
                            IdDispenser = 107,
                            NoWindow = "1000001"
                        },
                        new
                        {
                            Id = 8,
                            IdDispenser = 108,
                            NoWindow = "0001001"
                        },
                        new
                        {
                            Id = 9,
                            IdDispenser = 109,
                            NoWindow = "1000010"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<int>("IdDispenser")
                        .HasColumnType("int");

                    b.Property<int>("NoWindow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 3, 1, 9, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Stimea",
                            Flag = 0,
                            IdDispenser = 109,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 3, 1, 11, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Iladian",
                            Flag = 1,
                            IdDispenser = 108,
                            NoWindow = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 1, 16, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Maxigra",
                            Flag = 0,
                            IdDispenser = 107,
                            NoWindow = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2020, 3, 2, 6, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Limetic",
                            Flag = 1,
                            IdDispenser = 106,
                            NoWindow = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAndTime = new DateTime(2020, 3, 2, 9, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Stimea",
                            Flag = 1,
                            IdDispenser = 105,
                            NoWindow = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAndTime = new DateTime(2020, 3, 2, 18, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Iladian",
                            Flag = -1,
                            IdDispenser = 104,
                            NoWindow = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAndTime = new DateTime(2020, 3, 3, 8, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Maxigra",
                            Flag = 1,
                            IdDispenser = 103,
                            NoWindow = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAndTime = new DateTime(2020, 3, 3, 13, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Limetic",
                            Flag = 1,
                            IdDispenser = 102,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 9,
                            DateAndTime = new DateTime(2020, 3, 3, 17, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Stimea",
                            Flag = 1,
                            IdDispenser = 101,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 10,
                            DateAndTime = new DateTime(2020, 3, 4, 9, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Iladian",
                            Flag = -1,
                            IdDispenser = 102,
                            NoWindow = 2
                        },
                        new
                        {
                            Id = 11,
                            DateAndTime = new DateTime(2020, 3, 4, 14, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Maxigra",
                            Flag = 1,
                            IdDispenser = 103,
                            NoWindow = 2
                        },
                        new
                        {
                            Id = 12,
                            DateAndTime = new DateTime(2020, 3, 4, 18, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Limetic",
                            Flag = 0,
                            IdDispenser = 104,
                            NoWindow = 3
                        },
                        new
                        {
                            Id = 13,
                            DateAndTime = new DateTime(2020, 3, 5, 7, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Stimea",
                            Flag = 1,
                            IdDispenser = 105,
                            NoWindow = 3
                        },
                        new
                        {
                            Id = 14,
                            DateAndTime = new DateTime(2020, 3, 5, 8, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Iladian",
                            Flag = -1,
                            IdDispenser = 106,
                            NoWindow = 4
                        },
                        new
                        {
                            Id = 15,
                            DateAndTime = new DateTime(2020, 3, 5, 17, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Maxigra",
                            Flag = 1,
                            IdDispenser = 107,
                            NoWindow = 5
                        },
                        new
                        {
                            Id = 16,
                            DateAndTime = new DateTime(2020, 3, 6, 8, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Limetic",
                            Flag = 1,
                            IdDispenser = 108,
                            NoWindow = 6
                        },
                        new
                        {
                            Id = 17,
                            DateAndTime = new DateTime(2020, 3, 6, 21, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Stimea",
                            Flag = 1,
                            IdDispenser = 109,
                            NoWindow = 7
                        },
                        new
                        {
                            Id = 18,
                            DateAndTime = new DateTime(2020, 3, 7, 10, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Maxigra",
                            Flag = -1,
                            IdDispenser = 109,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 19,
                            DateAndTime = new DateTime(2020, 3, 7, 21, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Iladian",
                            Flag = 1,
                            IdDispenser = 109,
                            NoWindow = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.ListOfDispenser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAccount")
                        .HasColumnType("int");

                    b.Property<int>("IdDispenser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ListOfDispensers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdAccount = 1,
                            IdDispenser = 101
                        },
                        new
                        {
                            Id = 2,
                            IdAccount = 2,
                            IdDispenser = 102
                        },
                        new
                        {
                            Id = 3,
                            IdAccount = 3,
                            IdDispenser = 103
                        },
                        new
                        {
                            Id = 4,
                            IdAccount = 4,
                            IdDispenser = 104
                        },
                        new
                        {
                            Id = 5,
                            IdAccount = 5,
                            IdDispenser = 105
                        },
                        new
                        {
                            Id = 6,
                            IdAccount = 6,
                            IdDispenser = 106
                        },
                        new
                        {
                            Id = 7,
                            IdAccount = 7,
                            IdDispenser = 107
                        },
                        new
                        {
                            Id = 8,
                            IdAccount = 8,
                            IdDispenser = 108
                        },
                        new
                        {
                            Id = 9,
                            IdAccount = 9,
                            IdDispenser = 109
                        },
                        new
                        {
                            Id = 10,
                            IdAccount = 6,
                            IdDispenser = 101
                        },
                        new
                        {
                            Id = 11,
                            IdAccount = 6,
                            IdDispenser = 102
                        },
                        new
                        {
                            Id = 12,
                            IdAccount = 6,
                            IdDispenser = 104
                        },
                        new
                        {
                            Id = 13,
                            IdAccount = 7,
                            IdDispenser = 103
                        },
                        new
                        {
                            Id = 14,
                            IdAccount = 7,
                            IdDispenser = 109
                        },
                        new
                        {
                            Id = 15,
                            IdAccount = 8,
                            IdDispenser = 102
                        },
                        new
                        {
                            Id = 16,
                            IdAccount = 8,
                            IdDispenser = 109
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDispenser")
                        .HasColumnType("int");

                    b.Property<int>("NoWindow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAndTime = new DateTime(2020, 3, 20, 13, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Apap",
                            IdDispenser = 101,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAndTime = new DateTime(2020, 3, 21, 13, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Apap",
                            IdDispenser = 101,
                            NoWindow = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAndTime = new DateTime(2020, 3, 22, 13, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Apap",
                            IdDispenser = 101,
                            NoWindow = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAndTime = new DateTime(2020, 3, 20, 6, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "IBUM",
                            IdDispenser = 102,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 5,
                            DateAndTime = new DateTime(2020, 3, 20, 18, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "IBUM",
                            IdDispenser = 102,
                            NoWindow = 3
                        },
                        new
                        {
                            Id = 6,
                            DateAndTime = new DateTime(2020, 3, 21, 6, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "IBUM",
                            IdDispenser = 102,
                            NoWindow = 5
                        },
                        new
                        {
                            Id = 7,
                            DateAndTime = new DateTime(2020, 3, 20, 4, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "aaa",
                            IdDispenser = 103,
                            NoWindow = 2
                        },
                        new
                        {
                            Id = 8,
                            DateAndTime = new DateTime(2020, 3, 20, 23, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "aaa",
                            IdDispenser = 103,
                            NoWindow = 6
                        },
                        new
                        {
                            Id = 9,
                            DateAndTime = new DateTime(2020, 3, 20, 5, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "bbb",
                            IdDispenser = 104,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 10,
                            DateAndTime = new DateTime(2020, 3, 20, 4, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "ccc",
                            IdDispenser = 105,
                            NoWindow = 7
                        },
                        new
                        {
                            Id = 11,
                            DateAndTime = new DateTime(2020, 3, 25, 9, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "ddd",
                            IdDispenser = 106,
                            NoWindow = 4
                        },
                        new
                        {
                            Id = 12,
                            DateAndTime = new DateTime(2020, 3, 20, 1, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "brain",
                            IdDispenser = 107,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 13,
                            DateAndTime = new DateTime(2020, 3, 20, 2, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "brain",
                            IdDispenser = 107,
                            NoWindow = 7
                        },
                        new
                        {
                            Id = 14,
                            DateAndTime = new DateTime(2020, 3, 20, 5, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "lol",
                            IdDispenser = 108,
                            NoWindow = 4
                        },
                        new
                        {
                            Id = 15,
                            DateAndTime = new DateTime(2020, 3, 22, 16, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "lol",
                            IdDispenser = 108,
                            NoWindow = 7
                        },
                        new
                        {
                            Id = 16,
                            DateAndTime = new DateTime(2020, 3, 20, 16, 0, 1, 0, DateTimeKind.Unspecified),
                            Description = "Eutanazol",
                            IdDispenser = 109,
                            NoWindow = 1
                        },
                        new
                        {
                            Id = 17,
                            DateAndTime = new DateTime(2020, 3, 20, 17, 30, 1, 0, DateTimeKind.Unspecified),
                            Description = "Eutanazol",
                            IdDispenser = 109,
                            NoWindow = 6
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
