// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.API.Persistence.Contexts;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200310232950_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DispenserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Login = "Andrzej",
                            Password = "Tak1223"
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 100,
                            Login = "Moze",
                            Password = "Byc"
                        },
                        new
                        {
                            Id = 3,
                            DispenserId = 100,
                            Login = "Ten",
                            Password = "Trzeci"
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 101,
                            Login = "Oraz",
                            Password = "Czw"
                        },
                        new
                        {
                            Id = 5,
                            DispenserId = 102,
                            Login = "Koko",
                            Password = "Ro"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Dispenser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("TurnDiode")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Dispensers");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Cos",
                            TurnDiode = false
                        },
                        new
                        {
                            Id = 101,
                            Name = "Tam",
                            TurnDiode = true
                        },
                        new
                        {
                            Id = 102,
                            Name = "Yayy",
                            TurnDiode = false
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Historia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<int>("Flaga")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Okienka")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("History");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Datetime = new DateTime(2020, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Flaga = 0,
                            Nr_Okienka = 1,
                            Opis = "Stimea"
                        },
                        new
                        {
                            Id = 2,
                            Datetime = new DateTime(2020, 3, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 102,
                            Flaga = 1,
                            Nr_Okienka = 2,
                            Opis = "Iladian"
                        },
                        new
                        {
                            Id = 3,
                            Datetime = new DateTime(2020, 3, 8, 4, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 101,
                            Flaga = 0,
                            Nr_Okienka = 3,
                            Opis = "Maxigra"
                        },
                        new
                        {
                            Id = 4,
                            Datetime = new DateTime(2020, 3, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DispenserId = 103,
                            Flaga = 1,
                            Nr_Okienka = 4,
                            Opis = "Limetic"
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DispenserId")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Okienka")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispenserId = 101,
                            Nr_Okienka = 1,
                            Opis = "Stimea",
                            dateTime = new DateTime(2020, 3, 9, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DispenserId = 102,
                            Nr_Okienka = 2,
                            Opis = "Iladian",
                            dateTime = new DateTime(2020, 3, 9, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DispenserId = 102,
                            Nr_Okienka = 3,
                            Opis = "Maxigra",
                            dateTime = new DateTime(2020, 3, 9, 3, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DispenserId = 102,
                            Nr_Okienka = 4,
                            Opis = "Limetic",
                            dateTime = new DateTime(2020, 3, 9, 4, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication1.API.Domain.Models.Account", b =>
                {
                    b.HasOne("WebApplication1.API.Domain.Models.Dispenser", "Dispensers")
                        .WithMany()
                        .HasForeignKey("DispenserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
